import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import '../models/emergency_model.dart';

/// PDF generation service for safety reports
/// Creates downloadable safety reports after rescue
class PdfService {
  /// Generate safety report PDF
  Future<File> generateSafetyReport(EmergencyModel emergency) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Container(
                padding: const pw.EdgeInsets.all(20),
                color: PdfColors.red,
                child: pw.Text(
                  'SAFETY REPORT',
                  style: pw.TextStyle(
                    fontSize: 24,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.white,
                  ),
                ),
              ),
              pw.SizedBox(height: 20),

              // Report Details
              _buildReportSection('Incident Information', [
                _buildReportRow('Report ID', emergency.id),
                _buildReportRow('Date & Time', 
                  emergency.triggeredAt.toString()),
                _buildReportRow('Status', _getStatusText(emergency.status)),
              ]),

              pw.SizedBox(height: 20),

              // User Information
              _buildReportSection('User Information', [
                _buildReportRow('Name', emergency.userName),
                _buildReportRow('Phone', emergency.userPhone),
              ]),

              pw.SizedBox(height: 20),

              // Location Information
              _buildReportSection('Location Information', [
                _buildReportRow('Address', emergency.address),
                _buildReportRow('Latitude', emergency.latitude.toString()),
                _buildReportRow('Longitude', emergency.longitude.toString()),
                _buildReportRow('Google Maps', emergency.googleMapsLink),
              ]),

              pw.SizedBox(height: 20),

              // Police Response
              if (emergency.policeName != null)
                _buildReportSection('Police Response', [
                  _buildReportRow('Officer Name', emergency.policeName!),
                  if (emergency.policeArrivalTime != null)
                    _buildReportRow('Arrival Time', 
                      emergency.policeArrivalTime!),
                  if (emergency.rescueCompletedAt != null)
                    _buildReportRow('Rescue Completed', 
                      emergency.rescueCompletedAt.toString()),
                  _buildReportRow('Verification Status', 
                    emergency.isVerified ? 'Verified' : 'Not Verified'),
                ]),

              pw.SizedBox(height: 20),

              // Safety Notes
              if (emergency.safetyNotes != null)
                _buildReportSection('Safety Notes', [
                  pw.Text(emergency.safetyNotes!),
                ]),

              pw.Spacer(),

              // Footer
              pw.Container(
                padding: const pw.EdgeInsets.all(10),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.grey),
                ),
                child: pw.Text(
                  'This is an official safety report generated by Women Safety App',
                  style: const pw.TextStyle(fontSize: 10),
                ),
              ),
            ],
          );
        },
      ),
    );

    // Save PDF to file
    final output = await getTemporaryDirectory();
    final file = File('${output.path}/safety_report_${emergency.id}.pdf');
    await file.writeAsBytes(await pdf.save());

    return file;
  }

  /// Build report section
  pw.Widget _buildReportSection(String title, List<pw.Widget> children) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(5)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            title,
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 10),
          ...children,
        ],
      ),
    );
  }

  /// Build report row
  pw.Widget _buildReportRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 5),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 150,
            child: pw.Text(
              '$label:',
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.Expanded(
            child: pw.Text(value),
          ),
        ],
      ),
    );
  }

  /// Get status text
  String _getStatusText(EmergencyStatus status) {
    switch (status) {
      case EmergencyStatus.helpRequested:
        return 'Help Requested';
      case EmergencyStatus.policeOnTheWay:
        return 'Police On The Way';
      case EmergencyStatus.rescued:
        return 'Rescued';
      case EmergencyStatus.safetyConfirmed:
        return 'Safety Confirmed';
    }
  }

  /// Share PDF
  Future<void> sharePdf(File pdfFile) async {
    await Printing.sharePdf(
      bytes: await pdfFile.readAsBytes(),
      filename: pdfFile.path.split('/').last,
    );
  }

  /// Print PDF
  Future<void> printPdf(File pdfFile) async {
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdfFile.readAsBytes(),
    );
  }
}
