// File generated by FlutterFire CLI.
// This is a placeholder file. Run 'flutterfire configure' to generate the actual file.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9-WsSgXT7_-1YtJP-pJe4hVxxq1XABfg',
    appId: '1:104329471517:android:e678fca20e89638e3e08f4',
    messagingSenderId: '104329471517',
    projectId: 'sakhisamachar-f70d8',
    storageBucket: 'sakhisamachar-f70d8.firebasestorage.app',
  );

  // Run 'flutterfire configure' to generate this automatically

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDogIkcC7OCV6mhXZETVVatYVzbDALF4Yc',
    appId: '1:104329471517:ios:dbbb0fa99992b8933e08f4',
    messagingSenderId: '104329471517',
    projectId: 'sakhisamachar-f70d8',
    storageBucket: 'sakhisamachar-f70d8.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABFPZT5HdEsmO-bO04weXBn9kD0dOVgEA',
    appId: '1:104329471517:web:676049d205b5e2853e08f4',
    messagingSenderId: '104329471517',
    projectId: 'sakhisamachar-f70d8',
    authDomain: 'sakhisamachar-f70d8.firebaseapp.com',
    storageBucket: 'sakhisamachar-f70d8.firebasestorage.app',
    measurementId: 'G-1ZHTHFG7D5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDogIkcC7OCV6mhXZETVVatYVzbDALF4Yc',
    appId: '1:104329471517:ios:dbbb0fa99992b8933e08f4',
    messagingSenderId: '104329471517',
    projectId: 'sakhisamachar-f70d8',
    storageBucket: 'sakhisamachar-f70d8.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABFPZT5HdEsmO-bO04weXBn9kD0dOVgEA',
    appId: '1:104329471517:web:af61203ad266d84b3e08f4',
    messagingSenderId: '104329471517',
    projectId: 'sakhisamachar-f70d8',
    authDomain: 'sakhisamachar-f70d8.firebaseapp.com',
    storageBucket: 'sakhisamachar-f70d8.firebasestorage.app',
    measurementId: 'G-JEQB5MBVW3',
  );

}